import os

# Define the folder and file structure
structure = {
    "resume_job_matcher": {
        "requirements.txt": "",
        "main.py": "",
        "config": {
            "settings.py": ""
        },
        "agents": {
            "__init__.py": "",
            "resume_agent.py": "",
            "job_description_agent.py": "",
            "matching_agent.py": ""
        },
        "models": {
            "__init__.py": "",
            "data_models.py": ""
        },
        "utils": {
            "__init__.py": "",
            "pdf_reader.py": "",
            "text_processor.py": ""
        },
        "workflows": {
            "__init__.py": "",
            "matching_workflow.py": ""
        },
        "tests": {
            "__init__.py": "",
            "test_agents.py": ""
        }
    }
}


def create_structure(base_path, structure):
    for name, content in structure.items():
        path = os.path.join(base_path, name)
        if isinstance(content, dict):
            os.makedirs(path, exist_ok=True)
            create_structure(path, content)
        else:
            with open(path, 'w') as f:
                f.write(f"# {name} - autogenerated template file\n")


if __name__ == "__main__":
    create_structure(".", structure)
    print("Project structure created successfully.")
