# settings.py - autogenerated template file
from pydantic_settings import BaseSettings
from typing import Optional
import os
from dotenv import load_dotenv

load_dotenv()

class Settings(BaseSettings):
    """Application settings and configuration"""
    
    # OpenAI Configuration
    openai_api_key: str = os.getenv("OPENAI_API_KEY", "")
    openai_model: str = "gpt-3.5-turbo"
    temperature: float = 0.1
    max_tokens: int = 2000
    
    # Agent Configuration
    resume_agent_name: str = "ResumeAnalyzer"
    job_agent_name: str = "JobDescriptionAnalyzer"
    matching_agent_name: str = "SkillMatcher"
    
    # Processing Configuration
    min_job_descriptions: int = 5
    max_job_descriptions: int = 10
    similarity_threshold: float = 0.6
    
    # File Processing
    max_file_size_mb: int = 10
    supported_formats: list = ["pdf"]
    
    class Config:
        env_file = ".env"
        env_file_encoding = "utf-8"

# Global settings instance
settings = Settings()